# NumPy 


O NumPy é uma Biblioteca de Álgebra Linear para Python, o motivo pelo qual é tão importante para a Ciência de Dados com Python é que quase todas as bibliotecas do Ecossistema PyData confiam no NumPy como um de seus principais blocos de construção.

O Numpy também é rápido, pois possui ligações para as bibliotecas C. Para obter mais informações sobre por que você gostaria de usar matrizes em vez de listas, confira em [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

## Instruções de instalação

** É altamente recomendável instalar o Python usando a distribuição Anaconda para garantir que todas as dependências subjacentes (como as bibliotecas de álgebra linear) sejam sincronizadas com o uso de uma instalação conda. Se você possui o Anaconda, instale o NumPy acessando o terminal ou prompt de comando e digitando: **
    
    conda install numpy
    
**Se você não possui o Anaconda e não pode instalá-lo, consulte a documentação oficial do Numpy em várias instruções de instalação.(http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Usando NumPy

Depois de instalar o NumPy, você pode importá-lo como uma biblioteca:

In [2]:
import numpy as np

O Numpy possui muitas funções e recursos internos. Não abordaremos todos eles, mas focaremos alguns dos aspectos mais importantes do Numpy: vetores, matrizes, matrizes e geração de números. Vamos começar discutindo matrizes.

# Numpy Arrays

As matrizes NumPy são a principal maneira de usarmos o Numpy ao longo do curso. Matrizes numpy vêm basicamente em dois sabores: vetores e matrizes. Os vetores são estritamente matrizes 1-d e matrizes são 2-d (mas você deve observar que uma matriz ainda pode ter apenas uma linha ou uma coluna).

Vamos começar nossa introdução explorando como criar matrizes NumPy.

## Criando matrizes NumPy

### De uma lista Python

Podemos criar uma matriz convertendo diretamente uma lista ou lista de listas:

In [10]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [11]:
np.array(my_list)

array([1, 2, 3])

In [12]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Métodos internos

Existem várias maneiras internas de gerar matrizes


### arange

Retorne valores espaçados uniformemente dentro de um determinado intervalo.

In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])


### zeros e uns

Gere matrizes de zeros ou uns

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace

Retornar números espaçados uniformemente em um intervalo especificado.

In [6]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,50)

## eye


Cria uma matriz de identidade

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

O Numpy também tem várias maneiras de criar matrizes de números aleatórios:

### rand
Crie uma matriz da forma especificada e preencha-a com
amostras aleatórias de uma distribuição uniforme
sobre `` [0, 1) ``.

In [16]:
np.random.rand(2)

array([0.26034422, 0.40153852])

In [15]:
np.random.rand(5,5)

array([[0.42929898, 0.91816959, 0.1951565 , 0.71979498, 0.72208241],
       [0.94954708, 0.55362056, 0.14764312, 0.23748023, 0.73779305],
       [0.34871244, 0.51099707, 0.65500753, 0.52477794, 0.69686754],
       [0.86744022, 0.19432362, 0.85170512, 0.32777284, 0.85222191],
       [0.69782976, 0.46401706, 0.23842078, 0.08996179, 0.51424192]])

### randn


Retorne uma amostra (ou amostras) da distribuição "normal normal". Ao contrário do rand, que é uniforme:

In [17]:
np.random.randn(2)

array([-0.85366715,  2.15511891])

In [28]:
np.random.randn(5,5)

array([[-0.9132335 ,  0.56724211, -0.90562657, -0.43722816,  0.63561907],
       [-0.83809167, -0.88875564, -0.84855962, -0.12132338,  0.80049216],
       [ 0.4536121 ,  1.01081926, -2.61424304,  0.14443305,  0.48289063],
       [ 1.00870965, -1.64416427,  0.84240266,  1.67061103, -0.12373211],
       [-3.16667372,  0.56455642, -0.31915443,  0.52223881, -0.04062962]])

### randint
Retorne números inteiros aleatórios de `baixo` (inclusive) para` alto` (exclusivo).

In [26]:
np.random.randint(1,100)

30

In [27]:
np.random.randint(1,100,10)

array([72, 32, 42, 45, 58, 94, 45, 47, 20, 89])


## Atributos e métodos de matriz

Vamos discutir alguns atributos e métodos úteis ou uma matriz:

In [29]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr

array([24, 17, 20,  6, 47, 39, 42,  1, 32, 18])

## Reshape
Retorna uma matriz que contém os mesmos dados com uma nova forma.

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

Estes são métodos úteis para encontrar valores máximos ou mínimos. Ou para encontrar seus locais de índice usando argmin ou argmax

In [33]:
ranarr

array([24, 17, 20,  6, 47, 39, 42,  1, 32, 18])

In [34]:
ranarr.max()

47

In [35]:
ranarr.argmax()

4

In [36]:
ranarr.min()

1

In [37]:
ranarr.argmin()

7

## Shape

Shape is an attribute that arrays have (not a method):

In [38]:
# Vector
arr.shape

(25,)

In [39]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [40]:
arr.reshape(1,25).shape

(1, 25)

In [41]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [42]:
arr.reshape(25,1).shape

(25, 1)

### dtype


Você também pode pegar o tipo de dados do objeto na matriz:

In [43]:
arr.dtype

dtype('int32')


# Bom trabalho!